spring:
  datasource:
    url: "jdbc:mariadb://127.0.0.1:3309/chattergpt"
    username: root
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  devtools:
    add-properties: true
    livereload:
      enabled: true
logging:
  level:
    web: debug

stripe:
  api:
    key: ${STRIPE_API_KEY}
    product: ${STRIPE_10_EURO_PRODUCT_ID}

openai:
  api:
    url: "https://api.openai.com/v1/completions"
    key: ${OPENAI_API_KEY}
    models:
      - "text-davinci-003"
    max_tokens: 256
    temperature: 1
    presence_penalty: 0.6
    top_p: 1
    n: 1