spring:
  datasource:
    url: "jdbc:mariadb://127.0.0.1:3309/chattergpt"
    username: root
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  devtools:
    add-properties: true
    livereload:
      enabled: true
logging:
  level:
    web: debug
