# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    container_name: mariadb_chattergpt
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${DATASOURCE_PASSWORD}"
    ports:
      - "3309:3306"

